question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, "
             "you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

external_questions = [{"type": "boolean", "difficulty": "easy", "category": "Sports",
                       "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Film",
                       "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy", "category": "Geography",
                       "question": "Vatican City is a country.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy", "category": "History",
                       "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Books",
                       "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational children&#039;s book series&#039; name.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Japanese Anime &amp; Manga",
                       "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Science: Computers",
                       "question": "Linux was first created as an alternative to Windows XP.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Video Games",
                       "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Music",
                       "question": "The song &quot;Stronger Than You&quot; is a single by Estelle, who played Garnet in Steven Universe.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Film",
                       "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Video Games",
                       "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy", "category": "Animals",
                       "question": "A caterpillar has more muscles than humans do.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Japanese Anime &amp; Manga",
                       "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Science: Computers",
                       "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Science: Computers",
                       "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Video Games",
                       "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy", "category": "Animals",
                       "question": "The Killer Whale is considered a type of dolphin.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Video Games",
                       "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"type": "boolean", "difficulty": "easy", "category": "Geography",
                       "question": "The Republic of Malta is the smallest microstate worldwide.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"type": "boolean", "difficulty": "easy",
                       "category": "Entertainment: Video Games",
                       "question": "Peter Molyneux was the founder of Bullfrog Productions.",
                       "correct_answer": "True", "incorrect_answers": ["False"]}]
